#!/usr/bin/env python2.7

import os
import shutil
import sys

def get_tools_directory():
	""" get the location of the Hound tools directory """
	return os.path.realpath(os.path.dirname(__file__))

def has_valid_location(tools):
	""" ensure that the repository is in the GOPATH """
	parts = [x.lower() for x in tools.split(os.sep)]
	return parts[-5:-1] == ['src', 'github.com', 'etsy', 'hound']

def process(src, dst, filenames, op):
	""" process the filenames from source and use op to produce them in dst """
	for filename in filenames:
		target = os.path.join(dst, filename)
		if os.path.exists(target):
			continue
		op(os.path.join(src, filename), target)

def main():
	tools = get_tools_directory()
	if not has_valid_location(tools):
		print >> sys.stderr, "The Hound repository should be in a directory like:"
		print >> sys.stderr, "src/github.com/etsy/hound"
		print >> sys.stderr, ""
		print >> sys.stderr, "Follow the directions at https://github.com/etsy/hound#editing--building"
		return 1
	work = os.path.join(tools, '..', '..', '..', '..', '..')

	process(tools, work, ['Makefile', 'hound.sublime-project'], os.symlink)
	process(tools, work, ['config.json'], shutil.copy)

	return 0

if __name__ == '__main__':
  sys.exit(main())
