package vcs

import "encoding/json"

func init() {
	Register(newArchive, "archive")
}

type ArchiveDriver struct {
	IgnoredFiles []string `json:"ignored-files"`
}

func newArchive(b []byte) (Driver, error) {
	d := ArchiveDriver{}

	if b != nil {
		if err := json.Unmarshal(b, &d); err != nil {
			return nil, err
		}
	}

	return &d, nil
}

func (g *ArchiveDriver) HeadRev(dir string) (string, error) {
	return "n/a", nil
}

func (g *ArchiveDriver) Pull(dir string) (string, error) {
	return g.HeadRev(dir)
}

func (g *ArchiveDriver) Clone(dir, url string) (string, error) {
	return g.HeadRev(dir)
}

func (g *ArchiveDriver) SpecialFiles() []string {
	return g.IgnoredFiles
}

func (g *ArchiveDriver) AutoGeneratedFiles(dir string) []string {
	return []string{}
}
